export default {
  ADD_OR_MODIFY_CANVAS_ITEM: 'ADD_OR_MODIFY_CANVAS_ITEM',
  COPY_CANVAS_ITEM: 'COPY_CANVAS_ITEM',
  HIGHLIGHT_CANVAS_ITEM: 'HIGHLIGHT_CANVAS_ITEM',
  MODIFY_CANVAS_ITEM: 'MODIFY_CANVAS_ITEM',
  REMOVE_CANVAS_ITEM: 'REMOVE_CANVAS_ITEM',
  REMOVE_SELECTED_CANVAS_ITEM: 'REMOVE_SELECTED_CANVAS_ITEM',
  SET_PREVIEW_CANVAS_ITEM: 'SET_PREVIEW_CANVAS_ITEM',
  SET_SELECTED_CANVAS_ITEM: 'SET_SELECTED_CANVAS_ITEM',
  UNSET_PREVIEW_CANVAS_ITEM: 'UNSET_PREVIEW_CANVAS_ITEM',
  UPDATE_CURRENT_ACTION: 'UPDATE_CURRENT_ACTION',
  UPDATE_CURRENT_ACTION_FILL: 'UPDATE_CURRENT_ACTION_FILL',
  UPDATE_CURRENT_ACTION_LINE: 'UPDATE_CURRENT_ACTION_LINE',
};